"""alter migration

Revision ID: 2395affc7089
Revises: 34185f7f42db
Create Date: 2023-01-18 16:27:34.825663

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2395affc7089'
down_revision = '34185f7f42db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ih_user_profile', sa.Column('mobile', sa.String(length=11), nullable=False))
    op.drop_index('phone_num', table_name='ih_user_profile')
    op.create_unique_constraint(None, 'ih_user_profile', ['mobile'])
    op.drop_column('ih_user_profile', 'phone_num')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ih_user_profile', sa.Column('phone_num', mysql.VARCHAR(length=11), nullable=False))
    op.drop_constraint(None, 'ih_user_profile', type_='unique')
    op.create_index('phone_num', 'ih_user_profile', ['phone_num'], unique=False)
    op.drop_column('ih_user_profile', 'mobile')
    # ### end Alembic commands ###
